
trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - 'source/DockerFile'
    
pool:
  vmImage: ubuntu-latest

jobs:
  - job: BuildandpushImage
    displayName: 'Create image from the Dockerfile'
    steps:
    - task: Docker@2
      displayName: dockerbuild
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        addBaseImageData: false
    - task: Docker@2
      displayName: dockerpush
      inputs:
        command: 'push'
        addBaseImageData: false
