# tracker pipeline
# 
name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(rev:rrrr)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'terraform/cluster creation'

pool:
  vmImage: windows-latest

variables:
  - group : Terraform-varibales
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: serviceConnection 
    value: matrubhashaai_project
  - name: terraformFolder 
    value: '$(Build.SourcesDirectory)/terraform/cluster creation'

jobs:
  - job: Terraformresourcecreation
    displayName: Terraform Resource Creation
    steps:
      - checkout: self
        lfs: true
        displayName: 'checking out'
      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            cd '$(terraformFolder)'
            ls
      
      - task: TerraformTask@5
        displayName: Terrafor init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformFolder)'
          backendServiceArm: '$(serviceConnection)'
          backendAzureRmStorageAccountName: 'matrubhashaai'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        displayName: Terraform validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(terraformFolder)'
      
      - task: TerraformTask@5
        displayName: Terraform plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(terraformFolder)'
          commandOptions: '-var subscription_id=$(subscriptionId)'
          environmentServiceNameAzureRM: '$(serviceConnection)'
        

      - task: TerraformTask@5
        displayName: Terraform Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(terraformFolder)'
          environmentServiceNameAzureRM: '$(serviceConnection)'
        env:
          subscription_id: $(subscriptionId)