name: MatrubhashaAI-CD-$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pool:
  vmImage: windows-latest

resources:
  pipelines:
    - pipeline: MatrubhashaAI_Build
      source: MatrubhashaAI_Build
      branch: main
  
  repositories:
    - repository: githubRepo
      type: github
      name: Parshchakurkar/MatrubhashaAI
      endpoint: Parshchakurkar

variables:
  - group: CD pipeline variables

stages:
- stage: Dev
  jobs:
  - job: UpdateVersionInHelm
    displayName: Update Version In Helm
    steps:
      - download: MatrubhashaAI_Build
        artifact: tag
        displayName: Download the tag.txt
      - checkout: githubRepo
        persistCredentials: true
      
      - task: PowerShell@2
        displayName: Get the image version
        inputs:
          targetType: 'inline'
          script: |
            $tagFile = "$env:Pipeline_Workspace\MatrubhashaAI_Build\tag\tag.txt"
            if (!(Test-Path $tagFile)) {
                Write-Error "tag.txt not found!"
                exit 1
            }
            cd "$env:Pipeline_Workspace\MatrubhashaAI_Build"
            ls
            $version = Get-Content $tagFile -Raw
            Write-Host "Version from tag.txt: $version"
            # Set pipeline variable
            Write-Host "##vso[task.setvariable variable=ReleaseVersion]$version"
      
      - task: PowerShell@2
        displayName: Install Github CLI
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "Installing GitHub CLI..."
            $installer = "ghsetup.exe"
            Invoke-WebRequest -Uri "https://github.com/cli/cli/releases/download/v2.83.1/gh_2.83.1_windows_arm64.msi" -OutFile $installer
            Start-Process msiexec.exe -ArgumentList "/i $installer /quiet /qn /norestart" -Wait
            Write-Host "GitHub CLI Installed Successfully!"

      - task: PowerShell@2
        displayName: Config User for Git
        inputs:
          targetType: 'inline'
          script: |
            git config --global user.name "GitHub Sync Bot"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            $repoUrl = "https://$env:GITHUB_PAT@github.com/Parshchakurkar/MatrubhashaAI.git"
            git remote set-url origin $repoUrl
            $repoDir = "$env:Build_SourcesDirectory\githubrepo"
            if (Test-Path $repoDir) {
                Write-Host "Repo already exists. Pulling updates..."
                git pull origin main
            }
            else {
                Write-Host "Cloning fresh..."
                git clone $repoUrl $repoDir
            }
            cd $repoDir
            $branchName = "update-tag-$(Get-Date -Format yyyyMMddHHmmss)"
            git checkout -b $branchName
            git branch
            $filePath = Join-Path $repoDir "\helm\argocd\Dev\values.yaml"
            if (!(Test-Path $filePath)) {
                Write-Error "values.yaml not found at: $filePath"
                exit 1
            }
            Write-Host "Updating tag in values.yaml to $(ReleaseVersion) "
            (Get-Content $filePath) -replace 'tag:\s*.*', "tag: $(ReleaseVersion)" |  Set-Content $filePath
            git add .
            git commit -m "Update tag to $(ReleaseVersion)"
            git push --set-upstream origin $branchName
            Write-Host "##vso[task.setvariable variable=devbranchName]$branchName"
        env:
          GITHUB_PAT: $(GitHubPAT) 
        
      - task: PowerShell@2
        displayName: Raise PR
        inputs:
          targetType: 'inline'
          script: |
            git config --global user.name "GitHub Sync Bot"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            $env:GH_TOKEN = $env:GITHUB_PAT
            $token = $env:GH_TOKEN
            $token | gh auth login --with-token 
            $repoDir = "$env:Build_SourcesDirectory\githubrepo"
            gh pr create --title "Update tag to $(ReleaseVersion)" --body "Automated update of tag value to $(ReleaseVersion)" --base main --head $(devbranchName)
        env:
          GITHUB_PAT: $(GitHubPAT)