#Developer : Prashant Chakurkar
# date: 03/09/2025

name: $(Build.DefinitionName)_$(Build.SourceBranchName)_1.0.0.$(rev:rrrr)

#variables:


pool:
    vmImage: windows-latest

jobs:
    - job: Build
      displayName: Build Application
      steps:
          - checkout: self

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                cd "$env:BUILD_SOURCESDIRECTORY/source"
                ls
          - task: NuGetCommand@2
            displayName: Nuget restore
            inputs:
              command: 'restore'
              restoreSolution: '*/MatrubhashaAI.sln'
              feedsToUse: 'config'
          
          - task: VSBuild@1
            displayName: 'Matrubhasha build'
            inputs:
              solution: '*/MatrubhashaAI.sln'
              configuration: 'Release'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'mkdir $env:BUILD_SOURCESDIRECTORY/Setup'

          - task: CopyFiles@2
            displayName: 'Copy Files'
            inputs:
              SourceFolder: "$(Build.SourceDirectory)/source/bin/Release/net8.0/"
              Contents: '**'
              TargetFolder: "$(Build.SourceDirectory)/Setup"
              OverWrite: true
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.SourceDirectory)/Setup"
              artifact: 'Setup'
              publishLocation: 'pipeline'


    