# tracker pipeline
# 
name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(rev:rrrr)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'terraform/cluster creation'
      - 'Pipeline/matrubhashaInfrastructurepipeline.yml'

pool:
  vmImage: windows-latest

variables:
  - group : Terraform-varibales
  - name: serviceConnection 
    value: matrubhashaai_project
  - name: terraformFolder 
    value: '$(Build.SourcesDirectory)/terraform/cluster creation'
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

jobs:
  - job: ScanIAC
    displayName: Scan IAC
    steps:
      - checkout: self
      - task: Bash@3
        displayName: 'Install Snyk'
        inputs:
          targetType: 'inline'
          script: |
            npm install -g snyk

      - task: Bash@3
        displayName: 'Authenticate Snyk'
        inputs:
          targetType: 'inline'
          script: 'snyk auth $(SNYK_TOKEN)'
          workingDirectory: '$(terraformFolder)'
        env:
          SNYK_TOKEN: $(SNYK_TOKEN)

      - task: Bash@3
        displayName: 'Snyk Test on Terraform modules'
        inputs:
          targetType: 'inline'
          script: 'snyk iac test . --report --severity-threshold=high'
          workingDirectory: '$(terraformFolder)'
        env:
          SNYK_TOKEN: $(SNYK_TOKEN)

  - job: Terraformresourcecreation
    displayName: Terraform Resource Creation
    dependsOn: ScanIAC
    steps:
      - checkout: self
        lfs: true
        displayName: 'checking out'
      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformFolder)'
          backendServiceArm: '$(serviceConnection)'
          backendAzureRmStorageAccountName: 'matrubhashaai'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        displayName: Terraform validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(terraformFolder)'
      
      - task: TerraformTask@5
        displayName: Terraform plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(terraformFolder)'
          commandOptions: '-var subscription_id=$(subscriptionId)'
          environmentServiceNameAzureRM: '$(serviceConnection)'
        

  - job: Manualvalidation
    displayName: Manual validation approval
    dependsOn: Terraformresourcecreation
    pool: server
    steps:
      - task: ManualValidation@1
        displayName: manualvalidation
        condition: and(succeeded(),eq(variables.isMain, 'true')) 
        inputs:
          notifyUsers: 'parshchakurkar@gmail.com'
          approvers: 'parshchakurkar@gmail.com'
          instructions: 'review and approve'
          
  - job: TerraformApply
    displayName: Terraform Apply
    dependsOn: Manualvalidation
    steps:
      - checkout: self
        lfs: true
      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformFolder)'
          backendServiceArm: '$(serviceConnection)'
          backendAzureRmStorageAccountName: 'matrubhashaai'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'terraform.tfstate'
          
      - task: TerraformTask@5
        displayName: Terraform Apply
        condition: and(succeeded(),eq(variables.isMain, 'true'))
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(terraformFolder)'
          commandOptions: '-var subscription_id=$(subscriptionId)'
          environmentServiceNameAzureRM: '$(serviceConnection)'