#Developer : Prashant Chakurkar
# date: 03/09/2025

name: $(Build.DefinitionName)_$(Build.SourceBranchName)_1.0.0.$(rev:rrrr)

#variables:


pool:
    vmImage: windows-latest

jobs:
    - job: Build
      displayName: Build Application
      steps:
          - checkout: self

          - task: NuGetCommand@2
            displayName: Nuget restore
            inputs:
              command: 'restore'
              restoreSolution: '*/MatrubhashaAI.sln'
              feedsToUse: 'config'
          
          - task: VSBuild@1
            displayName: 'Matrubhasha build'
            inputs:
              solution: '*/MatrubhashaAI.sln'
              configuration: 'Release'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'mkdir $env:BUILD_SOURCESDIRECTORY/Setup'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                cd "$env:BUILD_SOURCESDIRECTORY/source/bin/Release/net8.0/"
                ls

          - task: CopyFiles@2
            displayName: 'Copy Files'
            inputs:
              SourceFolder: '$(build.sourceDirectory)/source/bin/Release/net8.0/'
              Contents: |
                MatrubhashaAI.exe 
                MatrubhashaAI.dll
              TargetFolder: '$(build.sourceDirectory)/Setup'
              OverWrite: true

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(build.sourceDirectory)/Setup'
              artifact: 'Setup'
              publishLocation: 'pipeline'


    