# tracker pipeline
# 
name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(rev:rrrr)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'terraform/cluster creation'
      - 'Pipeline/matrubhashaInfrastructurepipeline.yml'

pool:
  vmImage: windows-latest

variables:
  - group : Terraform-varibales
  - name: serviceConnection 
    value: matrubhashaai_project
  - name: terraformFolder 
    value: '$(Build.SourcesDirectory)/terraform/cluster creation'

jobs:
  - job: Terraformresourcecreation
    displayName: Terraform Resource Creation
    steps:
      - checkout: self
        lfs: true
        displayName: 'checking out'
      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            cd '$(terraformFolder)'
            ls
      
      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformFolder)'
          backendServiceArm: '$(serviceConnection)'
          backendAzureRmStorageAccountName: 'matrubhashaai'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        displayName: Terraform validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(terraformFolder)'
      
      - task: TerraformTask@5
        displayName: Terraform plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(terraformFolder)'
          commandOptions: '-var subscription_id=$(subscriptionId)'
          environmentServiceNameAzureRM: '$(serviceConnection)'
        

  - job: Manualvalidation
    displayName: Manual validation approval
    dependsOn: Terraformresourcecreation
    pool: server
    steps:
      - task: ManualValidation@1
        displayName: manualvalidation
        #condition: startswith(variables['Build.SourceBranch'], 'ref/heads/main')
        inputs:
          notifyUsers: 'parshchakurkar@gmail.com'
          approvers: 'parshchakurkar@gmail.com'
          instructions: 'review and approve'
          
  - job: TerraformApply
    displayName: Terraform Apply
    dependsOn: Manualvalidation
    steps:
      - checkout: self
        lfs: true
      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        displayName: Terraform init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformFolder)'
          backendServiceArm: '$(serviceConnection)'
          backendAzureRmStorageAccountName: 'matrubhashaai'
          backendAzureRmContainerName: 'terraform'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTask@5
        displayName: Terraform Apply
        #condition: eq(variables['Build.SourceBranch'], 'ref/heads/main')
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(terraformFolder)'
          commandOptions: '-var subscription_id=$(subscriptionId)'
          environmentServiceNameAzureRM: '$(serviceConnection)'