name: $(Build.DefinitionName)_$(Build.SourceBranchName)_1.00.00.$(rev:rrrr)
pr:
  branches:
    include:
      - main
  paths:
    include: 
      - 'source/DockerFile'


variables: 
  serviceConnection : matrubhashaai_project
  ACRname: matrubhashaaiacr
  AcrPrefix: matrubhashaaiacr.azurecr.io
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: ubuntu-latest

jobs:
  - job: BuildandpushImage
    displayName: 'Create image from the Dockerfile'
    steps:
    - task: Docker@1
      displayName: Dockerbuild
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: '$(serviceConnection)'
        azureContainerRegistry: '$(AcrPrefix)'
        command: 'Build an image'
        dockerFile: 'source/DockerFile'
        imageName: 'matrubhashaai:$(Build.BuildId)'

# push only when there is trigger from main branch
    - task: Docker@1
      displayName: Docker image push
      condition: and(succeeded(),eq(variables.isMain, true)) 
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscriptionEndpoint: '$(serviceConnection)'
        azureContainerRegistry: '$(AcrPrefix)'
        command: 'Push an image'
        imageName: 'matrubhashaai:$(Build.BuildId)'
