name: $(Build.DefinitionName)_$(Build.SourceBranch)_$(rev:rrrr)

trigger:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

variables:
  snycServiceConnection : snyk-connection
  snycProjectName: 'Parshchakurkar/MatrubhashaAI'
  snyOrg : 'parshchakurkar' 

jobs:
  - job: SnykScan
    displayName: 'Snyk Scan'
    steps:
      - checkout: self

      - task: NuGetCommand@2
        displayName: 'Nuget Restore'
        inputs:
          command: 'restore'
          restoreSolution: '$(Build.SourcesDirectory)/source/MatrubhashaAI.sln'
          feedsToUse: 'select'
          vstsFeed: 'fb72fbac-d94e-45b7-96d4-7f2990641340'
      - task: SnykSecurityScan@1
        displayName: 'Snyk Scan - app code'
        inputs:
          serviceConnectionEndpoint: '$(snycServiceConnection)'
          testType: 'app'
          failOnIssues: false
          projectName: '$(snycProjectName)'
          organization: '$(snyOrg)'
          testDirectory: '$(Build.SourcesDirectory)/source'
          additionalArguments: '--exlude = $(Build.SourcesDirectory)/source/DockerFile,$(Build.SourcesDirectory)/source/.dockerignore'
      
      - task: SnykSecurityScan@1
        displayName: 'Docker File Scan container'
        inputs:
          serviceConnectionEndpoint: '$(snycServiceConnection)'
          testType: 'container'
          dockerImageName: 'matrubhashaai'
          dockerfilePath: '$(Build.SourceDirectory)/source/DockerFile'
          monitorWhen: 'always'
          failOnIssues: true
          projectName: '$(snycProjectName)'
          organization: '$(snyOrg)'

      - task: SnykSecurityScan@1
        displayName: 'Snyk scan - IAC and k8s'
        inputs:
          serviceConnectionEndpoint: '$(snycServiceConnection)'
          testType: 'code'
          failOnIssues: false
          projectName: '$(snycProjectName)'
          organization: '$(snyOrg)'
          additionalArguments: '--exclude=Pipeline,source'
          failOnThreshold: 'high'
