name: $(Build.DefinitionName)_$(Build.SourceBranch)_$(rev:rrrr)

trigger:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

jobs:
  - job: SnykScan
    displayName: 'Snyk Scan'
    steps:
      - checkout: self
      - task: SnykSecurityScan@1
        displayName: snyk scan
        inputs:
          serviceConnectionEndpoint: 'snyk-connection'
          testType: 'app'
          severityThreshold: 'high'
          monitorWhen: 'always'
          failOnIssues: false
          projectName: 'Parshchakurkar/MatrubhashaAI'
          organization: 'parshchakurkar'
